### ISSUE TITLE
Publish progress?

### ISSUE THREAD

**Issue by benthemonkey** [sasstools/scss-tokenizer#4]
See [this sass lint issue](https://github.com/sasstools/sass-lint/issues/427). I heard there may be unpublished progress with regards to parsing Sass/SCSS into an AST. Is this the case?

Thanks!

**Comment by xzyfer** [comment]
This is just the tokenizer. AFAIK it's functional and capable of parsing any scss code thrown at it. I'll work on getting the test suite sorted and adding travis integration. There well be additional modules for handling the parsing and ASTs which I haven't had time to do yet. 

Please see my reply to your comment in https://github.com/sasstools/sass-lint/issues/427#issuecomment-160243370
