### ISSUE TITLE
Update babel - Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

### ISSUE THREAD

**Issue by jharris4** [sasstools/scss-tokenizer#8]
I just started getting the following warning when installing node-sass (which depends on this package):

```
warning node-sass > sass-graph > scss-tokenizer > babel-core > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

I'm assuming this is because this project/package depends on babel-core ^5.4.3.

babel-core 5.x has a dependency on minimatch ^2.0.3 whereas babel-core 6.x has a dependency on minimatch ^3.0.2

**Comment by xzyfer** [comment]
Fixed by #11
